assignment/assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam.urls')),
]

assignment/exam/urls.py
from django.contrib import admin
from django.urls import path, include

from exam.views import *

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('add', Add.as_view(), name="add"),
    path('edit/<pk>', Edit.as_view(), name="edit"),
    path('delete/<pk>', Edit.delete, name="delete"),
]

assignment/exam/models.py
from django.db import models


# Create your models here.
class Answers(models.Model):
    answer_text = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        db_table = "answers"


class Questions(models.Model):
    answer = models.ForeignKey(Answers, related_name='question_answer', null=True, on_delete=models.CASCADE)
    question_text = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = "questions"

assignment/exam/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from exam.models import *

from mysql.connector import MySQLConnection, Error
from configparser import ConfigParser


def read_db_config(filename='config.ini', section='mysql'):
    """ Read database configuration file and return a dictionary object
    :param filename: name of the configuration file
    :param section: section of database configuration
    :return: a dictionary of database parameters
    """
    # create parser and read ini configuration file
    parser = ConfigParser()
    parser.read(filename)

    # get section, default to mysql
    db = {}
    if parser.has_section(section):
        items = parser.items(section)
        for item in items:
            db[item[0]] = item[1]
    else:
        raise Exception('{0} not found in the {1} file'.format(section, filename))

    return db


class Home(ListView):
    model = Questions
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):

        """ connect to Mysql """
        db_config = read_db_config()
        db = None
        try:
            db = MySQLConnection(**db_config)
            if db.is_connected():
                cursor = db.cursor()
                query = "select questions.id, questions.question_text, answers.answer_text from questions join answers on (answers.id=questions.answer_id);"
                cursor.execute(query)
                questions_objs = cursor.fetchall()

                return render(request, self.template_name, {'questions_objs': questions_objs})
        except Error as e:
            print(e)
            return render(request, self.template_name)
        finally:
            if db is not None and db.is_connected():
                db.close()


class Add(CreateView):
    model = Questions
    template_name = "add.html"
    fields = ('question_text',)

    def post(self, request, *args, **kwargs):
        question_text = self.request.POST['question_text']
        answer_text = self.request.POST['answer_text']

        """ connect to Mysql """
        db_config = read_db_config()
        db = None
        try:
            db = MySQLConnection(**db_config)
            if db.is_connected():
                cursor = db.cursor()

                answer_insert_query = "insert into answers (answer_text) values ('%s')" % (answer_text)
                cursor.execute(answer_insert_query)
                answer_id = cursor.lastrowid
                db.commit()

                question_insert_query = "insert into questions (question_text, answer_id) values ('%s', %s)" % (question_text, answer_id)
                cursor.execute(question_insert_query)
                db.commit()

                return redirect(reverse('home'))
        except Error as e:
            print(e)
            return render(request, self.template_name)
        finally:
            if db is not None and db.is_connected():
                db.close()


class Edit(UpdateView):
    model = Questions
    template_name = "edit.html"

    def get(self, request, *args, **kwargs):
        question_id = self.kwargs['pk']

        """ connect to Mysql """
        db_config = read_db_config()
        db = None
        try:
            db = MySQLConnection(**db_config)
            if db.is_connected():
                cursor = db.cursor()
                query = "select questions.question_text, answers.answer_text from questions join answers on (questions.answer_id = answers.id) where questions.id = %s" % (question_id)
                cursor.execute(query)
                exam_obj = cursor.fetchone()

                return render(request, self.template_name, {'exam_obj': exam_obj})
        except Error as e:
            print(e)
            return render(request, self.template_name)
        finally:
            if db is not None and db.is_connected():
                db.close()

    def post(self, request, *args, **kwargs):
        question_id = self.kwargs['pk']
        question_text = self.request.POST['question_text']
        answer_text = self.request.POST['answer_text']

        """ connect to Mysql """
        db_config = read_db_config()
        db = None
        try:
            db = MySQLConnection(**db_config)
            if db.is_connected():
                cursor = db.cursor()

                query = "UPDATE questions, answers SET questions.question_text = '%s', answers.answer_text = '%s' where questions.id = %s and answers.id = questions.answer_id" % (question_text, answer_text, question_id)
                cursor.execute(query)
                db.commit()

                return redirect(reverse('home'))
        except Error as e:
            print(e)
            return render(request, self.template_name)
        finally:
            if db is not None and db.is_connected():
                db.close()

    def delete(self, *args, **kwargs):
        question_id = kwargs['pk']

        """ connect to Mysql """
        db_config = read_db_config()
        db = None
        try:
            db = MySQLConnection(**db_config)
            if db.is_connected():
                cursor = db.cursor()

                query = "DELETE answers, questions FROM answers left join questions on (answers.id = questions.answer_id) WHERE questions.id = %s" % (
                    question_id)
                cursor.execute(query)
                db.commit()

                return redirect(reverse('home'))
        except Error as e:
            print(e)
            return render(self.request, self.template_name)
        finally:
            if db is not None and db.is_connected():
                db.close()

assignment/assignment/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Dashboard{% endblock Title %} | Exam </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        header {
            width: 100%;
            height: 80px;
            overflow: hidden;
            {#position: fixed;#}
            top: 0;
            left: 0;
            z-index: 999;
            color: #ffffff;
            background-color: #0683c9;
            -webkit-transition: height 0.3s;
            -moz-transition: height 0.3s;
            -o-transition: height 0.3s;
            transition: height 0.3s;
        }
        header .header-container{
            margin: 12px 0;
        }
        a{
            color: inherit;
            text-decoration: none;
            transition: all 0.3s;
        }
    </style>
    {% block styles %}

    {% endblock styles %}
</head>
<body>
    <header>
        <div class="header-container">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-md-6">
                        <h1 id="logo">
                            <a href="{% url 'home' %}">Assignment</a>
                        </h1>
                    </div>
                    <div class="col-md-6 center-block"></div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a class="navbar-brand">Navbar</a>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
    </div>

    {% block content %}

    {% endblock %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>
</html>

assignment/exam/templates/add.html
{% extends 'base/base.html' %}

{% block styles %}
    <style>
        #addExam {
            margin: 40px 0;
        }
        a:hover {
            color: inherit;
            text-decoration: none;
        }
    </style>
{% endblock styles %}

{% block content %}
    <div class="container">
        <div id="addExam">
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="id_question_text">Question:</label>
                    <textarea name="question_text" cols="40" rows="5" class="form-control" maxlength="200" id="id_question_text"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_answer_text">Answer:</label>
                    <textarea name="answer_text" cols="40" rows="5" class="form-control" maxlength="200" id="id_answer_text"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

assignment/exam/templates/edit.html
{% extends 'base/base.html' %}

{% block styles %}
    <style>
        #addExam {
            margin: 40px 0;
        }
        a:hover {
            color: inherit;
            text-decoration: none;
        }
    </style>
{% endblock styles %}

{% block content %}
    <div class="container">
        <div id="addExam">
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="id_question_text">Question:</label>
                    <textarea name="question_text" cols="40" rows="5" class="form-control" maxlength="200" id="id_question_text">{{ exam_obj.0 }}</textarea>
                </div>
                <div class="form-group">
                    <label for="id_answer_text">Answer:</label>
                    <textarea name="answer_text" cols="40" rows="5" class="form-control" maxlength="200" id="id_answer_text">{{ exam_obj.1 }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

assignment/exam/templates/home.html
{% extends 'base/base.html' %}

{% block styles %}
    <style>
        .table thead th {
            border: none;
        }
        .table tbody tr td a{
            color: #007bff;
        }
        #addBtn {
            margin: 15px 0;
        }
        .wrapper {
            display: flex;
            align-items: stretch;
        }

        #sidebar {
            width: 250px;
            z-index: 999;
            background: #0683c9;
            color: #fff;
            transition: all 0.3s;
        }
        #sidebar .sidebar-header {
            padding: 20px;
            background: #0683c9;
        }
        #sidebar ul p {
            color: #fff;
            padding: 10px;
        }
        #sidebar ul li a {
            padding: 10px;
            font-size: 1.1em;
            display: block;
        }
        #sidebar ul li a:hover {
            color: #7386D5;
            background: #fff;
        }

        #sidebar ul li.active > a, a[aria-expanded="true"] {
            color: #fff;
            background: #6d7fcc;
        }
        p {
            font-family: 'Poppins', sans-serif;
            font-size: 1.1em;
            font-weight: 300;
            line-height: 1.7em;
            color: #999;
        }

        a, a:hover, a:focus {
            color: inherit;
            text-decoration: none;
            transition: all 0.3s;
        }
    </style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="wrapper">
                <!-- Sidebar -->
                <nav id="sidebar">
                    <div class="sidebar-header">
                        <h3>Sidebar</h3>
                    </div>

                    <ul class="list-unstyled components">
                        <p>Heading</p>
                        <li class="">
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="col-md-9">
            <a id="addBtn" href="{% url 'add' %}" class="btn btn-primary">Add Question and Answer</a>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Question</th>
                    <th scope="col">Answer</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                {% if questions_objs %}
                    {% for questions_obj in questions_objs %}
                    <tr>
                        <td>{{ questions_obj.1 }}</td>
                        <td>{{ questions_obj.2 }}</td>
                        <td>
                            <a href="{% url 'edit' questions_obj.0 %}">Edit</a>&nbsp;{{ nom }}&nbsp;
                            <a href="{% url 'delete' questions_obj.0 %}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5">No Data Found.</td>
                    </tr>
                {% endif %}
                </tbody>

            </table>
        </div>
    </div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"></script>
</div>
{% endblock %}